project:
  type: website
  title: "Recovering Biological Inference from Non-Standard RNA-Seq"
  output-dir: "_site"
  render:
    - index.qmd

format:
  revealjs:
    controls: true
    progress: true
    slide-number: c/t
    center: false
    transition: fade
    transition-speed: fast
    chalkboard: false
    navigation-mode: linear
    controls-layout: bottom-right
    hash: true
    auto-stretch: false
    theme:
      - default
      - assets/styles/theme.scss
    include-after-body:
      - assets/includes/after-body.html
    embed-resources: false

execute:
  echo: false
  warning: false
  error: false
